### ISSUE TITLE
BuildWindow

### ISSUE THREAD

**Issue by yves1706** [LiubovRukhlina/InProgress#39]
### Code

- [x] Add the action listeners
- [x] does not close after building
- [ ] building SpaceStation does not work
- [x] Deploying Gates does not work
- [x] Removing of Resources from the list is not working (or the list is not updating correctly)

**Comment by Sahejpalarneja** [comment]
I think the removing will work, I was refilling the inventory every time we create a window for testing.
Building robots sometimes raises an exception as the RandomTravel function has not been implemented correctly.
