### ISSUE TITLE
TransportGates after Explosion

### ISSUE THREAD

**Issue by yves1706** [LiubovRukhlina/InProgress#5]
`Asteroid` need to know its`Gate` and vice versa.
The connections is needed for travel

A1->T1->T2->A2

And when an `Asteroid` explodes its `Gate` must be deactivated 
`explode()`  method in `Uranium` must be updated too.

**Comment by Sahejpalarneja** [comment]
modified setCurrentLocation()
Changed Asteroid.hasGate to public 
Created TransportGate tg in Asteroid class
Added if statement to explode
modified deactivateTransportGate
